"""Public context-store API for Lerim's simplified DB-only architecture."""

from lerim.context.embedding import (
    EMBEDDING_DIMS,
    EMBEDDING_MODEL_NAME,
    EmbeddingProvider,
    clear_embedding_provider_cache,
    get_embedding_provider,
)
from lerim.context.project_identity import ProjectIdentity, resolve_project_identity
from lerim.context.spec import (
    ALLOWED_FINDING_LEVELS,
    ALLOWED_KINDS,
    ALLOWED_STATUSES,
    DURABLE_RECORD_KINDS,
    DURABLE_FINDING_LEVELS,
    IMPLEMENTATION_FINDING_LEVELS,
    MAX_DURABLE_BODY_CHARS,
    MAX_EPISODE_BODY_CHARS,
    MAX_EPISODE_OUTCOMES_CHARS,
    MAX_EPISODE_USER_INTENT_CHARS,
    MAX_EPISODE_WHAT_HAPPENED_CHARS,
    MAX_RECORD_TITLE_CHARS,
    RECORD_KIND_SPECS,
    format_durable_record_kinds,
    format_allowed_finding_levels,
    normalize_finding_level,
    normalize_record_kind,
    normalize_record_payload,
    normalize_record_status,
    record_search_text,
    record_validation_message,
)
from lerim.context.store import ContextStore, SearchHit

__all__ = [
    "ALLOWED_FINDING_LEVELS",
    "ALLOWED_KINDS",
    "ALLOWED_STATUSES",
    "ContextStore",
    "DURABLE_RECORD_KINDS",
    "DURABLE_FINDING_LEVELS",
    "EMBEDDING_DIMS",
    "EMBEDDING_MODEL_NAME",
    "EmbeddingProvider",
    "IMPLEMENTATION_FINDING_LEVELS",
    "MAX_DURABLE_BODY_CHARS",
    "MAX_EPISODE_BODY_CHARS",
    "MAX_EPISODE_OUTCOMES_CHARS",
    "MAX_EPISODE_USER_INTENT_CHARS",
    "MAX_EPISODE_WHAT_HAPPENED_CHARS",
    "MAX_RECORD_TITLE_CHARS",
    "ProjectIdentity",
    "RECORD_KIND_SPECS",
    "SearchHit",
    "clear_embedding_provider_cache",
    "format_durable_record_kinds",
    "format_allowed_finding_levels",
    "get_embedding_provider",
    "normalize_finding_level",
    "normalize_record_kind",
    "normalize_record_payload",
    "normalize_record_status",
    "record_search_text",
    "record_validation_message",
    "resolve_project_identity",
]
