"""Shared timeout contracts for Lerim local server and model calls."""

from __future__ import annotations

ANSWER_REQUEST_TIMEOUT_SECONDS = 300
HTTP_API_POST_TIMEOUT_SECONDS = ANSWER_REQUEST_TIMEOUT_SECONDS + 30

BAML_HTTP_CONNECT_TIMEOUT_MS = 10_000
BAML_HTTP_TIME_TO_FIRST_TOKEN_TIMEOUT_MS = ANSWER_REQUEST_TIMEOUT_SECONDS * 1_000
BAML_HTTP_IDLE_TIMEOUT_MS = ANSWER_REQUEST_TIMEOUT_SECONDS * 1_000
BAML_HTTP_REQUEST_TIMEOUT_MS = ANSWER_REQUEST_TIMEOUT_SECONDS * 1_000
